#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.url=jdbc:mysql://localhost:3306/student?useSSL=false&useUnicode=true&characterEncoding=utf-8
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/student?useSSL=false&useUnicode=true&characterEncoding=utf-8
  data:
    redis:
      port: 6379
      host: localhost
server:
  port: 8401
logging:
  level:
    com.example: debug
#mybatis-plus:
#  type-aliases-package: com.example.studentcurriculum_backend_springboot.student.entity
#  global-config:
#    banner: false
#    db-config:
#      id-type: input